export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 2000,
  },
  {
    name: "Apr",
    "Active User": 2780,
  },
  {
    name: "May",
    "Active User": 1890,
  },
  {
    name: "Jun",
    "Active User": 2390,
  },
  {
    name: "Jul",
    "Active User": 3490,
  },
  {
    name: "Aug",
    "Active User": 3410,
  },
  {
    name: "Sep",
    "Active User": 3090,
  },
  {
    name: "Oct",
    "Active User": 1410,
  },
  {
    name: "Nov",
    "Active User": 2490,
  },
  {
    name: "Dec",
    "Active User": 3750,
  },
];

export const rows = [
  {
    id: 1,
    name: "kirubel",
    nameOfCompany: "kirub plc",
    email: "kirub@gmail.com",
    country: "Ethiopia",
    city: "Addis Ababa",
    product: "Ceramics",
    tinNumber: "TN4567893746",
    tradingLicenceNo: "TL8348747567",
    verified: "True",
    createdAt: "12/3/2022",
  },
  {
    id: 2,
    name: "kirubel",
    nameOfCompany: "kirub plc",
    email: "kirub@gmail.com",
    country: "Ethiopia",
    city: "Addis Ababa",
    product: "Ceramics",
    tinNumber: "TN4567893746",
    tradingLicenceNo: "TL8348747567",
    verified: "True",
    createdAt: "12/3/2022",
  },
  {
    id: 3,
    name: "kirubel",
    nameOfCompany: "kirub plc",
    email: "kirub@gmail.com",
    country: "Ethiopia",
    city: "Addis Ababa",
    product: "Ceramics",
    tinNumber: "TN4567893746",
    tradingLicenceNo: "TL8348747567",
    verified: "True",
    createdAt: "12/3/2022",
  },
  {
    id: 4,
    name: "kirubel",
    nameOfCompany: "kirub plc",
    email: "kirub@gmail.com",
    country: "Ethiopia",
    city: "Addis Ababa",
    product: "Ceramics",
    tinNumber: "TN4567893746",
    tradingLicenceNo: "TL8348747567",
    verified: "True",
    createdAt: "12/3/2022",
  },
  {
    id: 5,
    name: "kirubel",
    nameOfCompany: "kirub plc",
    email: "kirub@gmail.com",
    country: "Ethiopia",
    city: "Addis Ababa",
    product: "Ceramics",
    tinNumber: "TN4567893746",
    tradingLicenceNo: "TL8348747567",
    verified: "True",
    createdAt: "12/3/2022",
  },
];
